### ISSUE TITLE
Feature request: support alpha format #<AA><color>

### ISSUE THREAD

**Issue by neeasade** [emacsfodder/kurecolor#13]
eg with `kurecolor-decrease-brightness-by-step` and a brightness-step of 2:

`#ffcccccc` should be `#ffc6c6c6`, not `#f9c7c7`

**Comment by jasonm23** [comment]
If you would like to submit a pull request the feature would be considered.

Note the test suite would have to be updated to include tests (all passing) for the feature.

**Comment by jasonm23** [comment]
Hex colors in the format `#rrggbbaa` RGBA are supported.  Although at the moment only a few functions support alpha hex colors.

- Hex RGBA to css RGBA
- Hex RGBA to XCode colorLiteral
