### ISSUE TITLE
defexamples -> ETD -> MELPA -> external dependency.

### ISSUE THREAD

**Issue by jasonm23** [emacsfodder/kurecolor#15]
@magnars - I really like what you started with `defexamples`.

I've implemented a version of the same toolkit here on Kurecolor so I can develop defexamples into a full package. 

I was working on something similar here for docs: https://github.com/jasonm23/.doom.d/blob/master/plugins/elisp-to-markdown.el

**Comment by jasonm23** [comment]
- [x] Single macros for both testing and docs, using a swtich flag. `etd-testing t` (`nil` to make docs)
- [x] Setup Github actions and test on Emacs 28.1
- [x] Test on 26.1..29.0
- [x] Push etd.el out to it's own package.

**Comment by jasonm23** [comment]
https://github.com/emacsfodder/etd

**Comment by jasonm23** [comment]
Development of etd should begin here and port things to the etd repo, so we don't need to think up trite examples... yet.

**Comment by jasonm23** [comment]
https://github.com/melpa/melpa/pull/8194

**Comment by jasonm23** [comment]
Awaiting MELPA so I can make ETD a development dependency

**Comment by jasonm23** [comment]
Added ETD to MELPA,

- [x] Remove the etd files in this repo and use the package instead.

@tarsius it'll require a PR to be done prior to 2023.

**Comment by jasonm23** [comment]
@tarsius @alphapapa fixed in 1a3b95a

**Comment by tarsius** [comment]
Thanks a lot!
