### ISSUE TITLE
problem with destructuring-bind

### ISSUE THREAD

**Issue by habamax** [emacsfodder/kurecolor#6]
I had to add `(require 'cl)` to be able to use the package.

I couldn't find it anywhere in package docs, is it intended?

**Comment by jasonm23** [comment]
Hi,  yes it's intentional, I'm using destructuring to fetch the color channels.

Thank you for catching, I have cl required in my .emacs.d so I missed this.

Will fix shortly

**Comment by jasonm23** [comment]
Melpa edge will have a new version soon

Fixed
