### ISSUE TITLE
Precision error

### ISSUE THREAD

**Issue by thblt** [emacsfodder/kurecolor#8]
Some transforms generate hex codes of more than 32 bits. For example,  applying

`C-u 100 M-x kurecolor-decrease-saturation-by-step` on `#ff0000`

results in

`#FF4FB4FB` (eight hex digits).

**Comment by jasonm23** [comment]
Thanks for reporting, I'll need to clamp to #FFFFFF

**Comment by jasonm23** [comment]
Recently added a kurecolor-clamp function.  I'll modify the adjust/set/increase/decrease functions to ensure returned/edited color values are valid.

**Comment by jasonm23** [comment]
Fixed in ad75b8bc40144322b9d0477368f45c05eada1c5d
